# Указываем версию Docker Compose
version: '3.9'

services:
  # Определяем название приложения в services.
  skill_tap:
    # Задаём название сети для контейнера.
    networks:
      - skill_tap
    # Задаём имя контейнера.
    container_name: skill_tap_container
    # Сообщаем что для сервиса надо запустить Dockerfile и указываем путь к нему.
    build:
      dockerfile: Dockerfile
    # Устанавливаем команду для применения миграций и для запуска сервера.
    command: >
       sh -c "python manage.py migrate && uvicorn skill_tap.asgi:application --host 0.0.0.0 --port 8000 & python telegram.py"
    # Параметр сопоставляющий порты между хостом(8000) и контейнером(8000).
    ports:
      - '8000:8000'
    # В параметр указываются приложения, которые должны быть запущены перед запуском приложения skill_tap.
    depends_on:
      - db
      - redis
    # Подгружаем глобальные (логин,пароль БД) переменные для БД из .env файла.
    env_file:
      - .env
    # Указываем что всё(все локальные изменения) в текущей директории должно быть доступно в контейнере.
    volumes:
      - .:/skill_tap
    # Контейнер будет перезапускаться, если он был остановлен, за исключением, когда он был остановлен вручную.
    restart: unless-stopped


  # Определяем название приложения в services.
  db:
    # Задаём название сети для контейнера.
    networks:
      - skill_tap
    # Задаём имя контейнера.
    container_name: db_skill_tap_container
    # Указываем какой образ использовать для запуска контейнера.
    image: postgres:16-alpine
    # Подгружаем переменные для БД из .env файла.
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Параметр сопоставляющий порты между хостом(5433) и контейнером(5432).
    ports:
      - '5433:5432'
    # Указываем том для хранения данных БД. Что бы не потерять данный при остановке контейнера.
    volumes:
      - db_data:/var/lib/postgresql/data
    # Контейнер будет перезапускаться, если он был остановлен, за исключением, когда он был остановлен вручную.
    restart: unless-stopped


  # Сервис Redis
  redis:
    # Задаём название сети для контейнера.
    networks:
      - skill_tap
    # Задаём имя контейнера.
    container_name: redis_container
    # Указываем какой образ использовать для запуска контейнера.
    image: redis:alpine
    # Параметр сопоставляющий порты между хостом(6379) и контейнером(6379).
    ports:
      - '6379:6379'
    # Контейнер будет перезапускаться, если он был остановлен, за исключением, когда он был остановлен вручную.
    restart: unless-stopped


  # Сервис Celery
  celery:
    # Задаём название сети для контейнера.
    networks:
      - skill_tap
    # Задаём имя контейнера.
    container_name: celery_container
    # Сообщаем что для сервиса надо запустить Dockerfile и указываем путь к нему.
    build:
      dockerfile: Dockerfile
    command: celery -A skill_tap worker --loglevel=info
    # В параметр указываются приложения, которые должны быть запущены перед запуском приложения celery.
    depends_on:
      - db
      - redis
    # Подгружаем глобальные переменные из .env файла.
    env_file:
      - .env
    # Указываем том для хранения данных celery. Что бы не потерять данный при остановке контейнера.
    volumes:
      - .:/skill_tap
    # Контейнер будет перезапускаться, если он был остановлен, за исключением, когда он был остановлен вручную.
    restart: unless-stopped


  # Сервис для Celery Beat.
  celery-beat:
    # Задаём название сети для контейнера.
    networks:
      - skill_tap
    # Задаём имя контейнера.
    container_name: celery_beat_container
    # Сообщаем что для сервиса надо запустить Dockerfile и указываем путь к нему.
    build:
      dockerfile: Dockerfile
    command: celery -A skill_tap beat --loglevel=info
    # В параметр указываются приложения, которые должны быть запущены перед запуском приложения celery beat.
    depends_on:
      - db
      - redis
    # Подгружаем глобальные переменные из .env файла.
    env_file:
      - .env
    # Указываем том для хранения данных celery. Что бы не потерять данный при остановке контейнера.
    volumes:
      - .:/skill_tap
    # Контейнер будет перезапускаться, если он был остановлен, за исключением, когда он был остановлен вручную.
    restart: unless-stopped


  pgadmin:
    # Задаём название сети для контейнера.
    networks:
      - skill_tap
    # Задаём имя контейнера.
    container_name: pgadmin_container
    # Указываем какой образ использовать для запуска контейнера.
    image: dpage/pgadmin4
    # Подгружаем переменные для админки из .env файла.
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    # Указываем том для хранения данных Админки БД. Что бы не потерять данный при остановке контейнера.
    volumes:
      - pgadmin:/var/lib/pgadmin
    # Параметр сопоставляющий порты между хостом и контейнером.
    ports:
      - '8080:8080'
    restart: unless-stopped


# Указываем глобально, какие volumes у нас есть.
volumes:
  db_data:
    driver: local
  pgadmin:
    driver: local


# Соединяем все контейнеры, где указана сеть skill_tap, в одну сеть.
networks:
  skill_tap:
    driver: bridge
