# Generated by Django 4.2.16 on 2024-12-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_task_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTopPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц записи')),
                ('tg_id', models.PositiveBigIntegerField(verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя игрока')),
                ('points', models.IntegerField(verbose_name='Очки игрока')),
                ('rank', models.IntegerField(verbose_name='Место в топ-100')),
            ],
            options={
                'verbose_name': 'Топ игрока за месяц',
                'verbose_name_plural': 'Топ игроков за месяц',
                'indexes': [models.Index(fields=['month'], name='app_core_mo_month_7ac4a5_idx')],
                'unique_together': {('month', 'rank')},
            },
        ),
    ]
