# Generated by Django 4.2.16 on 2024-12-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_monthlytopplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='instruction',
            field=models.BooleanField(default=True, verbose_name='Показ инструкции'),
        ),
    ]
