# Generated by Django 4.2.16 on 2024-12-12 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_player_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='Ник блогера')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('referral_link', models.URLField(unique=True, verbose_name='Реферальная ссылка')),
                ('referral_count', models.PositiveIntegerField(default=0, verbose_name='Количество приведённых пользователей')),
            ],
        ),
        migrations.AddField(
            model_name='referralsystem',
            name='blogger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='app_core.blogger', verbose_name='Блогер'),
        ),
    ]
