# Generated by Django 4.2.16 on 2024-12-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_blogger_referralsystem_blogger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'verbose_name': 'Блоггер>', 'verbose_name_plural': 'Блоггеры'},
        ),
        migrations.AlterField(
            model_name='referralsystem',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='app_core.player', verbose_name='Реферал'),
        ),
    ]
