# Generated by Django 4.2.16 on 2024-12-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0009_task_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна'),
        ),
    ]
