# Generated by Django 4.2.16 on 2024-12-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0013_alter_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(default='by', max_length=50, verbose_name='Страна'),
        ),
    ]
