# Generated by Django 4.2.16 on 2024-12-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0014_alter_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertask',
            name='add_flag',
            field=models.BooleanField(default=True, verbose_name='Доп. флаг'),
        ),
    ]
