# Generated by Django 4.2.16 on 2024-12-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0015_alter_playertask_add_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='login_today2',
            field=models.BooleanField(default=False, verbose_name='Входил ли пользователь сегодня'),
        ),
        migrations.AlterField(
            model_name='player',
            name='login_today',
            field=models.BooleanField(default=False, verbose_name='Входил ли пользователь сегодня для фронта'),
        ),
    ]
