# Generated by Django 4.2.16 on 2024-12-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на продукт'),
        ),
    ]
