name: Deploy to Server

on:
  push:
    branches:
      - main  # Запускать деплой только при пуш в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/tap_skillbox/tg_clicker_skillbox || exit
            git pull origin main
            docker-compose down
            docker-compose up -d --build
